sudo: required
services:
  - docker

before_install:
  - docker build -t mvasigh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mvasigh/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-course"
  env: "DockerReactCourse-env"
  bucket_name: "elasticbeanstalk-us-east-2-147115627535"
  bucket_path: "docker-react-course"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
